library-path = "/run/media/windy/iris/calibre"
pinyin-search-enabled = true
fuzzy-pinyin = [
    ["on", "ong"],
    ["an", "ang"],
    ["en", "eng"],
    ["in", "ing"]
]

[[columns]]
name = "title"
width-ratio = 40
fg = "White"
bg = "Reset"
selected-fg = "White"
selected-bg = "Blue"
header-fg = "Blue"
highlighted-match-fg = "Red"

[[columns]]
name = "author"
width-ratio = 20
fg = "Cyan"
bg = "Reset"
selected-fg = "White"
selected-bg = "Blue"
header-fg = "Blue"
highlighted-match-fg = "Red"

[[columns]]
name = "series"
width-ratio = 20
fg = "White"
bg = "Reset"
selected-fg = "White"
selected-bg = "Blue"
header-fg = "Blue"
highlighted-match-fg = "Red"

[[columns]]
name = "tags"

width-ratio = 20
fg = "Cyan"
bg = "Reset"
selected-fg = "White"
selected-bg = "Blue"
header-fg = "Blue"
highlighted-match-fg = "Red"

[colors]
search-box-border-fg = "Blue"
table-border-fg = "Blue"
search-box-title = "Blue"
search-box-text = "White"
table-title-fg = "Blue"
