library_path = ""

[filter]
# Supported: "pinyin", "romaji", "german-latin", "french-latin", "spanish-latin", "russian-latin"
# Plain original text search is always enabled.
translators = ["pinyin"]
pinyin_fuzzy = true
pinyin_fuzzy_groups = [
    ["on", "ong"],
    ["an", "ang"],
    ["en", "eng"],
    ["in", "ing"]
]
